### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-http-logger#1]
We want a middleware that dumps request payloads to the default log. If there's  a bug on a site, we at least will always have the users' submissions. This is critical for websites that have a contact form meant to generate leads.

The package will provide a middleware which users can register in a middleware stack or as route middleware.

Two important configurable features:

- We need a way to determine which requests we want to log. Our spatie/laravel-responsecache package does this elegantly by passing a class to in the configuration that determines wether a request should be cached. It might also be nice to define a method that pulls out the attributes that should be logged, so users have full control there too
- The config file should also have a blacklist array for attributes we never want to log. By default: `['password', 'password_confirmation']`, like Laravel's TrimStrings middleware

The config file could look like this:

```php
return [
    'log_profile' => Spatie\HttpLogger\DefaultLogger::class,
    
    'except' => [
        'password',
        'password_confirmation',
    ],
];
```

**Comment by bloggervista** [comment]
so it will be global middleware right. And will it affect the app speed ?

Thanks

**Comment by sebastiandedeyne** [comment]
In the grand scheme of things, logging something on a POST/PATCH request probably won't be a notable difference in speed.

Laravel middleware can be registered however you want, globally or on a per-route basis.

**Comment by jstoone** [comment]
@sebastiandedeyne have you started any development of this? If not, I'd love to contribute the initial implementation.

**Comment by sebastiandedeyne** [comment]
This is gonna be @brendt's first package here at Spatie, so we won't be accepting contributions for any initial code contributions :)

We're always open for feedback once we've got a first draft though!

**Comment by brendt** [comment]
Thanks! I'll be working on this package probably early next week, so I'll keep you posted.

**Comment by LKDevelopment** [comment]
@brendt just as a suggestion: With logfiles it is really hard on an HA Setup (with multiple servers), so there it would be better if the "lines" are stored as sample on a database.  It would be really nice, if there could be a logger + migration out of the box.

**Comment by brendt** [comment]
@LKDevelopment good point. At this point we're going to continue with the `DefaultLogProfile`, which will log Laravel's default log.

It will however be very simple to create a new `LogProfile`, or extend this existing one. So you'll definitely be able to do that, but it won't be provided out of the box - for now.

**Comment by freekmurze** [comment]
Closing this because everything in this issue has been implemented.
