### ISSUE TITLE
issue during install package 

### ISSUE THREAD

**Issue by khalafouy** [spatie/laravel-http-logger#12]
when I used composer require to install package .. it returns 

Could not find package spatie/laravel-http-logger at any version matching your PHP version 5.6.25.0

**Comment by AlexVanderbist** [comment]
This package requires at least version 7.0 of PHP. If you want to use this package you'll need to update PHP.

**Comment by kacanghijau** [comment]
Hello, i have an issue when install this package.. 
![image](https://user-images.githubusercontent.com/27037720/38983765-b9eece5e-43f7-11e8-8391-a8f40ddc9676.png)
