### ISSUE TITLE
unable to install the package

### ISSUE THREAD

**Issue by kacanghijau** [spatie/laravel-http-logger#14]
Hello, i have an issue when install this package.. 

![image](https://user-images.githubusercontent.com/27037720/38983765-b9eece5e-43f7-11e8-8391-a8f40ddc9676.png)

any idea to solve this issue? im using laravel 5.3

**Comment by nirwannursabda** [comment]
@kacanghijau  composer update using vpn. solve my case

if not, try updating composer to latest. using "composer self-update"
