### ISSUE TITLE
Error when using file input array Laravel 5.5

### ISSUE THREAD

**Issue by cyberfly** [spatie/laravel-http-logger#15]
File Input

<img src="http://i63.tinypic.com/289flfm.png" />

```
{
    "message": "Type error: Argument 1 passed to Spatie\\HttpLogger\\DefaultLogWriter::Spatie\\HttpLogger\\{closure}() must be an instance of Symfony\\Component\\HttpFoundation\\File\\UploadedFile, array given",
    "status_code": 500
}
```
Any idea how to fix this?

Thanks

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by juanvillegas** [comment]
@cyberfly as a temporary workaround you can just create a custom logger and swap it in the config file. The custom logger should just be the same as defaultlogwrite, but ignoring the files.
