### ISSUE TITLE
Response logger

### ISSUE THREAD

**Issue by cosmok** [spatie/laravel-http-logger#17]
Hi,

Thanks for the great package!

I have a requirement to log the response as well and I am happy to submit a PR, but, would like some feedback from the community:

1. Should I modify the existing middleware to also log the response (perhaps controlled via a flag)?
2. Should I be reusing some of the configs such as 'except' or new ones will make sense?

**Comment by freekmurze** [comment]
I'd like to keep the scope of this package small. 

If you want response logging start your own package. Or if you want to build on top of ours, feel free to fork our code.
