### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-http-logger#2]
The current tests only test for the bare minimum of scenarios.

For starters, the `DefaultLogProfileTest` only tests for `POST` and `GET` requests. Different scenarios should be added for `PUT`, `PATCH` and `DELETE`.

Second, the `IntegrationTest` can use some more scenarios to test real-world examples.

**Comment by LKDevelopment** [comment]
Don't miss `HEAD`, `OPTIONS` and `TRACE` :)
