### ISSUE TITLE
why no get request?

### ISSUE THREAD

**Issue by im-zhangxi** [spatie/laravel-http-logger#26]
`public function shouldLogRequest(Request $request): bool
    {
        return in_array(strtolower($request->method()), ['post', 'put', 'patch', 'delete']);
    }`

**Comment by freekmurze** [comment]
Because get requests mostly do not contain payloads that you'd want to inspect later.

**Comment by im-zhangxi** [comment]
> Because get requests mostly do not contain payloads that you'd want to inspect later.

when debug environment, I want to get the get request.
Could you please tell me what I should do?

**Comment by LeeWeiZhang** [comment]
@im-zhangxi 
inside the file config/http-logger.php:9 
```
'log_profile' => \Spatie\HttpLogger\LogNonGetRequests::class,
```

we can create our own class and replace it here, so you can add the get 
```
        return in_array(strtolower($request->method()), ['post', 'put', 'patch', 'delete']);
```
in your custom class

**Comment by im-zhangxi** [comment]
@LeeWeiZhang 
 Implemented, thank you
