### ISSUE TITLE
Response code whitelist/blacklist

### ISSUE THREAD

**Issue by eberkund** [spatie/laravel-http-logger#30]
It would be great if there was a configurable feature where only requests with certain response codes could be excluded or excluded. This would greatly reduce the amount of noise in the logs for people who don't have a special searchable log system setup.

For example, being able to exclude 200 responses. Or include only 400 or 500 errors.

I could probably submit a PR if there was any interest.

**Comment by freekmurze** [comment]
I think you could already achieve this by creating a custom `LogProfile`.
