### ISSUE TITLE
split up DefaultLogWriter::logRequest()

### ISSUE THREAD

**Issue by lsmith77** [spatie/laravel-http-logger#38]
Would you be open a to a PR to split this method by extracting a protected method “getMessage()” that basically does everything except for the call to `Log::info()`? This would make it feasible to extend the class in case one wants to store the data else where, f.e. in a DB. Potentially there should even be another “formatMessage()” method and “getMessage()” just provides an array of data. what do you think?

https://github.com/spatie/laravel-http-logger/blob/master/src/DefaultLogWriter.php#L12

**Comment by freekmurze** [comment]
Feel free to send a PR and I'll consider merging it in 👍
