### ISSUE TITLE
Better log output

### ISSUE THREAD

**Issue by brendt** [spatie/laravel-http-logger#4]
Currently, the log output is just a single line. There might be a better format.

Opinions are welcome.

**Comment by sebastiandedeyne** [comment]
We've done `print_r` in the past, there's probably a better solution though.

**Comment by brendt** [comment]
I like a JSON format, because you could copy/paste it right into a REST client.

Maybe the headers should also be logged?

**Comment by brendt** [comment]
As it seems, all newlines are stripped when using the `Log`. This results in difficult to read output.

**Comment by brendt** [comment]
Turns out Monolog can have different formatters, and you can make your own. Laravel also has its wrapper around this: `Illuminate\Log\Writer` in which formatter can be configured.

I didn't go as far as making our own formatter, but it seems like a possibility, enabling new lines. I don't think it's worth the time now, but might be a nice feature for the future.

**Comment by freekmurze** [comment]
> I like a JSON format, because you could copy/paste it right into a REST client.

I very much like this idea.

**Comment by brendt** [comment]
@freekmurze But the question about formatting in the log output itself still stands. What's your opinion? To format the JSON in a pretty way, we'll have to create a custom formatter.

Functionally the unformatted JSON output will of course work just as fine; so pretty format might not be that important.

**Comment by pmatseykanets** [comment]
It would be nice to separate concerns of 

- figuring out what requests to log or not `shouldLogRequest()`
- and format in which the log is being written `logRequest()`

This way regardless of logger/formatter requests that shouldn't be logged won't be.

**Comment by freekmurze** [comment]
That's a pretty good idea, let's do that @brendt .

**Comment by sebastiandedeyne** [comment]
Confused, isn't that what it looks like now? 🤔 

https://github.com/spatie/laravel-http-logger/blob/48f75eeba9cbcc87471f9c880e5a3288d29d504b/src/DefaultLogProfile.php

**Comment by brendt** [comment]
I share @sebastiandedeyne's confusion, or were you maybe @pmatseykanets was referring to further split it in separate classes?

**Comment by freekmurze** [comment]
Separating concerns will be handled in #7

Current log output is good enough for a v1.0.0
