### ISSUE TITLE
User logged

### ISSUE THREAD

**Issue by oswaldo89** [spatie/laravel-http-logger#43]
is possible to get the user id if there is logged ?

like that  `$user = Auth::user();`
regards!

**Comment by oswaldo89** [comment]
i found the solution.. mi project is only for use like API

in this case... in my file `auth.php` put this:

'defaults' => [
        'guard' => 'api', <<< ----
        'passwords' => 'users',
    ],


with this now i can get `Auth::user();` inside my middelwere

**Comment by h-kusaba-1001** [comment]
I had a similar issue.
However, `Auth:;user()` is null...

But, I found a solution.
I write it In `$middlewareGroups` in `App\Http\Kernel`.
Maybe it will be used before authentication, then user will be null.

If you can, add a line in `web` or so on in `$middlewareGroups` as I did.

( Maybe, it shoud be write in the readme 🤔 
Thank you!
