### ISSUE TITLE
Update to Laravel 11

### ISSUE THREAD

**Issue by scimsoft** [spatie/laravel-http-logger#63]
The documentation is not updated to Laravel 11, middleware configuration.
and I dont seem to get it to work,
Added the middleware to the bootstrap app.php like this
`
     ->withMiddleware(function (Middleware $middleware) {

        $middleware->append(\Spatie\HttpLogger\Middlewares\HttpLogger::class);
    })
`
but no log generated in the expected storage/logs directory
thnx

**Comment by timvandijck** [comment]
Hey @scimsoft the way you added the middleware should work.

I just tried it in a fresh Laravel 11 application and it worked fine. Note that by default the package does not log GET requests: `$middleware->append(\Spatie\HttpLogger\Middlewares\HttpLogger::class);`
