### ISSUE TITLE
working with php 5.6 version

### ISSUE THREAD

**Issue by hoangphison** [spatie/laravel-http-logger#8]
i currently working on laravel 5.4 and php 5.6, but this package required php 7.0. So can you team make it work with lower php version like 5.6 as minimal version. Thank you!

_English is not my native language. Sorry for any spelling mistakes._

**Comment by freekmurze** [comment]
Hi, for our projects we have been using PHP 7 for quite some time now. I’d doesn’t make sense for us to support a version of PHP that we don’t use and that will be unsupported very soon.

I highly suggest you upgrade to PHP 7. Alternatively fork our code and maintain your own PHP 5 compatible version.
